version: "3.3"

services:
  db:
    image: mysql:5.7.24
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: bhiWIinE3ZcqzSZh 

  phpmyadmin: 
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      
  redis:
    depends_on:
      - db
    image: "redis:4-alpine"
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass AliJApeLM4Sw1chF

volumes:
  db_data: {}
