version: "3.3"

services:
  db:
    image: mysql:5.7.24
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    networks: 
      - service_backend
    volumes:
      - ./config:/etc/mysql/conf.d  # 映射本地配置文件到容器中的my.cnf
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: eg907423 
      
  redis:
    depends_on:
      - db
    image: "redis:4-alpine"
    container_name: redis
    restart: always
    networks: 
      - service_backend
    ports:
      - "6379:6379"
    command: redis-server --requirepass eg907423

networks:
  service_backend:
    name: service_backend
    external: true
      
volumes:
  db_data: {}
